FROM node:6-alpine

WORKDIR /usr/src/app

COPY package.json /usr/src/app/
RUN npm install &&  npm cache clean

COPY . /usr/src/app

CMD ["npm", "start"]
# replace this with your application's default port
EXPOSE 6901

